{% set name = "swashes" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/swashes-{{ version }}.tar.gz
  sha256: dac39c32073b20d451e6bc88d8fb69e757d1bb947c91165e7247b7cd8c3ce62c

build:
  entry_points:
    - swashes = swashes:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - scikit-build-core >=0.11
    - pip
    - cmake >=3.18
  run:
    - python >={{ python_min }}

test:
  imports:
    - swashes
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest >=8.3.5
    - python {{ python_min }}

about:
  summary: A Python package for the SWASHES executable.
  license: CECILL-2.0
  license_file: LICENSE_en.txt
  dev_url: https://sourcesup.renater.fr/projects/swashes/

extra:
  recipe-maintainers:
    - lrntct
